(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1200,
	height: 600,
	fps: 50,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: []
};



lib.ssMetadata = [];


// symbols:



(lib.node = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.2)").s().p("AgqOiIrlmqQgsgbAAg0IABtRQgBg4AtgXILjmqQAsgbArAbILhGqQAvAcAAAzIAANRQAAAjgWAYQgLAMgPAIIrgGqQgWANgWAAQgUAAgWgNg");
	this.shape.setTransform(92.8,105.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FC4768","#F67FA1","#FDCD66"],[0,0.51,0.992],-0.3,-93.3,-0.1,93.2).s().p("AgwQRIs8ncQgyggAAg4IAAu4QABg9AxgbIM8ndQAwgeAyAeIM4HdQA1AeAAA6IAAO4QAAA5g1AfIs5HcQgZAPgYAAQgXAAgZgPg");
	this.shape_1.setTransform(92.7,105.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,185.5,211.3);


(lib.arrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AifERQgJgIAAgNIAAn3QAAgMAJgJQAIgIALgBQAJAAAHAGIEWDzQAGAGAEAJQAEAJABAIQgBAKgEAJQgEAJgGAFIkWDzQgHAFgJABQgLAAgIgJg");
	this.shape.setTransform(16.9,28.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,33.8,56.4);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.node("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.3,0.3,0.479,0.479,0,0,0,93.2,106.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.4,-50.6,88.9,101.3);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.node("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.3,0.3,0.479,0.479,0,0,0,93.2,106.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44.4,-50.6,88.9,101.3);


// stage content:
(lib.canvas = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		that = this;
		//console.log(this)
		
		if(!that.flag)
		{
			that.flag=true;
			
			// NEXT
			that.nextBtn.addEventListener("click", nextClicked);
			function nextClicked() {
				that.play();
			}
			
			// PREVIOUS
			that.prevBtn.addEventListener("click", prevClicked);
			function prevClicked() {
				that.addEventListener("tick", rewind);
			}
			function rewind(e) {
				//console.log(that["frame_"+(that.currentFrame - 1)], "frame_"+(that.currentFrame - 1), (that.currentFrame - 1))
				that.gotoAndStop((that.currentFrame + that.getDuration() - 1) % that.getDuration());
				if (that["frame_"+(that.currentFrame)] !== undefined)
					that.removeEventListener("tick", rewind);		
			}
		}
		this.stop();
	}
	this.frame_49 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(49).call(this.frame_49).wait(1));

	// prev
	this.prevBtn = new lib.arrow();
	this.prevBtn.parent = this;
	this.prevBtn.setTransform(36.9,300,1,1,180,0,0,16.9,28.2);
	this.prevBtn._off = true;

	this.timeline.addTween(cjs.Tween.get(this.prevBtn).wait(1).to({_off:false},0).wait(49));

	// next
	this.nextBtn = new lib.arrow();
	this.nextBtn.parent = this;
	this.nextBtn.setTransform(1163.1,300,1,1,0,0,0,16.9,28.2);

	this.timeline.addTween(cjs.Tween.get(this.nextBtn).wait(50));

	// Layer 7
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE1A5QgIgDgFgFQgGgGgEgIIgCgJIgBgKQAAgHADgKQAEgIAGgFQAFgGAIgDQAHgDAIAAQAIAAAIADQAHADAGAGQAGAFADAIQADAKAAAHIgDATQgDAIgGAGQgGAFgHADQgIADgIAAQgIAAgHgDgAE9gFQgDACgBADQgCACgBAEIgBAKIABAKIADAHQABAEADABQADACAEAAQAEAAADgCQADgBACgEIADgHIABgKIgBgKQgBgEgCgCQgCgDgDgCQgDgBgEAAQgEAAgDABgABmA5QgIgCgGgHQgGgFgDgIQgCgGgBgNQAAgGADgLQAEgHAFgGQAGgGAHgDQAHgDAIAAQAJAAAGADQAHADAFAGQAEAFACAHQACAFAAAJIAAALIgzAAQABAEACAEQACADADADIAGADIAIABIAJgBIAJgEIAIAOQgGAFgIACQgIADgHAAQgJAAgIgDgACCAHQAAgHgDgDQgCgCgCAAQgDgCgEAAQgGAAgEAEQgFADgBAHIAeAAIAAAAgAkeA5QgHgDgGgFQgGgGgDgIIgDgJIAAgKQAAgHADgKQADgIAGgFQAGgGAHgDQAIgDAIAAQAIAAAHADQAIADAFAGQAGAFADAIQAEAKAAAHIgEATQgDAIgGAGQgFAFgIADQgHADgIAAQgIAAgIgDgAkVgFQgDACgCADQgCACgBAEIgBAKIABAKQABAEACADQACAEADABQADACAEAAQAEAAACgCQADgBACgEIADgHIABgKIgBgKQgBgEgCgCIgFgFQgCgBgEAAQgEAAgDABgAnQA7IgLgDIgKgFIgJgHIAPgRQAGAFAHADQAHADAHAAQAHAAAEgCQAEgDAAgFQAAgFgEgCIgMgGIgOgGIgIgFIgIgEQgDgEgBgEQgCgGAAgGQAAgHADgFQADgGAFgFQAFgEAHgDQAIgDAIAAQAGAAANAEIAJAFIAIAGIgNAQQgGgFgFgCQgGgCgGAAQgGAAgEACQgEAEAAAEQAAAFAFACIAMAGIAOAFIAJAEIAHAGIAEAIIACALQAAAHgDAGQgDAGgFAFQgFAEgIADQgIADgKAAIgLgBgAG9A6IgMg6IAAAAIgMA6IgdAAIgVhSIAZAAIAMA+IABAAIAEgZIAKglIAVAAIAPA+IABAAIAMg+IAXAAIgUBSgAD3A6IAAgxQAAgJgDgCQgCgDgGAAQgEAAgEACQgDACgEACIAAA5IgZAAIAAh1IAZAAIgCAtIALgIQAIgEAHAAQAHAAAFACQAFADADAEQAEAEABAHQACAGAAAGIAAA0gAAnA6IAAgxQAAgJgCgCQgCgDgGAAQgDAAgEACQgDACgEACIAAA5IgXAAIAAgxQAAgJgDgCQgCgDgGAAQgDAAgDACQgEACgEACIAAA5IgZAAIAAhSIAUAAIACAKIABAAQAGgFAFgDQAHgEAHAAQAJAAAEAEQAFADADAHQAHgHAFgDIAHgDIAIgBQAHAAAFACQAFADADAEQADAEACAHQABAGAAAGIAAA0gAiVA6IgMg6IgBAAIgMA6IgcAAIgVhSIAYAAIAMA+IABAAIAFgZIAJglIAWAAIAPA+IAAAAIAMg+IAXAAIgUBSgAlcA6IAAgxQAAgJgDgCQgCgDgFAAQgFAAgDACQgEACgEACIAAA5IgZAAIAAh1IAZAAIgBAtIALgIQAHgEAIAAQAHAAAFACQAFADADAEQADAEABAHQACAGAAAGIAAA0g");
	this.shape.setTransform(599.9,405.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(49));

	// Layer 6
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(3,1,1).p("As7CvQhJhJAAhmQAAhmBJhJQA+g+BWgJIVPAAQBVAJA/A+QBJBJAABmQAABmhJBJQhJBIhnAAQAAAAgBAAI0YAAQhmAAhIhIg");
	this.shape_1.setTransform(599.8,405.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AKLD3I0YAAQhmAAhIhIQhJhJAAhmQAAhmBJhJQA+g+BWgJIVPAAQBVAJA/A+QBJBJAABmQAABmhJBJQhJBIhnAAIgBAAg");
	this.shape_2.setTransform(599.8,405.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).to({state:[]},1).wait(49));

	// Layer 4
	this.instance = new lib.Tween1("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(599.9,405.5);

	this.instance_1 = new lib.Tween2("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(599.9,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},49).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,y:300},49,cjs.Ease.get(1)).wait(1));

	// Layer 5
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("Ag8ByIAAjdIAfAAIAEAoIABAAQALgVAPgMQAQgNATAAQANABALAFIgHAgQgMgDgKgBQgQAAgNAMQgGAGgHAKQgHAKgFAOIAACNg");
	this.shape_3.setTransform(890.6,191.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AglBtQgUgJgOgOQgOgQgIgVQgJgWABgbQgBgZAJgXQAIgVAOgQQAOgPAUgHQASgIATAAQAUAAASAIQAUAHANAPQAPAQAIAVQAJAXAAAZQAAAbgJAWQgIAVgPAQQgNAOgUAJQgSAHgUAAQgTAAgSgHgAgZhOQgLAGgJAMQgIALgFAQQgEAQgBARQABATAEAQQAFAPAIAMQAJALALAGQAMAGANAAQAOAAALgGQAMgGAJgLQAIgMAFgPQAFgQgBgTQAAgRgEgQQgFgQgIgLQgJgMgMgGQgLgGgOAAQgNAAgMAGg");
	this.shape_4.setTransform(870.4,191.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgiClIAAi9IgfAAIAAgdIAfgCIAAgjQAAgSAEgNQAEgOAIgJQAIgKAKgFQAMgFARAAQATAAASAHIgJAdQgMgFgNAAQgPAAgIAKQgIALAAAWIAAAjIAvAAIAAAfIgvAAIAAC9g");
	this.shape_5.setTransform(854.7,186.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgrBrQgVgIgRgNIATgaQAQANAOAGQARAIARAAQAVAAAMgKQALgKAAgPQAAgIgFgHQgEgGgIgFQgJgHgXgJIgYgJQgNgEgIgHQgKgIgGgKQgGgLAAgNQAAgNAGgMQAFgLAKgJQAKgJAOgEQAOgFAQAAQAUAAATAHQAQAHAOALIgSAYQgMgKgLgEQgOgGgNAAQgSAAgLAKQgKAIAAAOQAAAOAPAKQAIAFAYAKIAYAJQANAGAJAFQAKAIAGAKQAGAMAAAPQAAAOgFALQgGANgKAJQgLAJgPAFQgPAFgUAAQgUAAgXgJg");
	this.shape_6.setTransform(831.9,191.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgSCeIAAjdIAkAAIAADdgAgRhzQgIgHAAgLQAAgKAIgHQAHgHAKAAQALAAAHAHQAIAHAAAKQAAALgIAHQgHAHgLAAQgKAAgHgHg");
	this.shape_7.setTransform(818.9,186.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgOCdQgLgFgIgKQgHgKgDgOQgEgNABgSIAAj5IBBAAIAAD8QAAAJAEAFQADAEAFAAIAIgBIAIAyQgMAGgVAAQgQAAgMgGg");
	this.shape_8.setTransform(802.5,186.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgoBvQgUgJgPgPQgRgQgIgVIgGgXIgDgbQAAgRAJggQAIgVARgQQAPgPAUgJQAUgHAUgBQAVABAUAHQAUAJAPAPQAQAQAJAVQAJAgAAARIgCAbIgHAXQgJAVgQAQQgPAPgUAJQgUAHgVABQgUgBgUgHgAgQg6QgIAEgGAIQgFAJgCAMQgDAMAAANQAAAPADAMQACALAFAJQAGAIAIAEQAHAFAJAAQAKAAAIgFQAHgEAGgIQAFgJADgLQACgNAAgOQAAgNgCgMQgDgMgFgJQgGgIgHgEQgIgFgKAAQgJAAgHAFg");
	this.shape_9.setTransform(784.1,191.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgYBvQgVgJgPgPQgPgQgJgVQgIgXAAgbQAAgRAJggQAJgVARgQQAQgPAWgJQATgHAYgBQAUAAASAIQAQAGAMAMIgeArQgQgOgQAAQgMAAgKAFQgIAEgHAIQgHAJgDAMQgEAMAAANQAAAOAEANQADALAHAJQAHAIAHAEQAKAFALAAQAQAAAYgQIAbAqQgQAOgUAHQgUAIgTAAQgWgBgUgHg");
	this.shape_10.setTransform(763.1,191.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgoBvQgUgJgPgPQgQgQgJgVIgGgXIgDgbQAAgRAJggQAJgVAQgQQAPgPAUgJQAUgHAUgBQAVABAUAHQAUAJAPAPQAQAQAJAVQAJAgAAARIgCAbIgHAXQgJAVgQAQQgPAPgUAJQgUAHgVABQgUgBgUgHgAgQg6QgIAEgGAIQgFAJgCAMQgDAMAAANQAAAPADAMQACALAFAJQAGAIAIAEQAHAFAJAAQAKAAAIgFQAHgEAGgIQAFgJACgLQADgNAAgOQAAgNgDgMQgCgMgFgJQgGgIgHgEQgIgFgKAAQgJAAgHAFg");
	this.shape_11.setTransform(741.4,191.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgFCMQgPgHgJgLQgJgMgFgQQgEgPAAgVIAAhaIgfAAIAAgyIAigDIAIg8IA2AAIAAA8IA2AAIAAA1Ig2AAIAABZQAAASAIAKQAHAJAOgBQAKABAMgFIAKAxQgcAIgWAAQgVAAgNgGg");
	this.shape_12.setTransform(722,188.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgoBvQgUgJgPgPQgRgQgIgVIgGgXIgDgbQAAgRAJggQAIgVARgQQAPgPAUgJQAUgHAUgBQAVABAUAHQAUAJAPAPQAQAQAJAVQAJAgAAARIgCAbIgHAXQgJAVgQAQQgPAPgUAJQgUAHgVABQgUgBgUgHgAgQg6QgIAEgGAIQgFAJgCAMQgDAMAAANQAAAPADAMQACALAFAJQAGAIAIAEQAHAFAJAAQAKAAAIgFQAHgEAGgIQAFgJADgLQACgNAAgOQAAgNgCgMQgDgMgFgJQgGgIgHgEQgIgFgKAAQgJAAgHAFg");
	this.shape_13.setTransform(702.6,191.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AhLB0IAAjhIA3AAIAEAoIACAAQAHgMAHgIQAFgJAJgFQARgMASAAQAQAAALAFIgLA6QgNgEgMAAQgOAAgNAKQgNALgHAVIAACCg");
	this.shape_14.setTransform(684.4,191);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AhvCVIAAkpIBsAAQAYAAAUAFQAWAGAPAKQARAMAIASQAJAbAAATIgCAYIgHAVQgJAQgRANQgPAMgWAHQgUAGgXAAIgpAAIAABlgAgsgEIAlAAQAMAAALgDQAKgDAHgGQAGgGAEgJQADgJAAgLQAAgMgDgIQgEgIgHgGQgHgEgKgDQgKgCgMAAIglAAg");
	this.shape_15.setTransform(662.9,187.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgFCMQgPgHgJgLQgJgMgFgQQgEgPAAgVIAAhaIgfAAIAAgyIAigDIAIg8IA2AAIAAA8IA2AAIAAA1Ig2AAIAABZQAAASAIAKQAHAJAOgBQAKABAMgFIAKAxQgcAIgWAAQgVAAgNgGg");
	this.shape_16.setTransform(634,188.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgYBvQgVgJgPgPQgPgQgJgVQgIgXAAgbQAAgRAJggQAJgVARgQQAQgPAWgJQATgHAYgBQAUAAASAIQAQAGAMAMIgeArQgQgOgQAAQgMAAgKAFQgIAEgHAIQgHAJgDAMQgEAMAAANQAAAOAEANQADALAHAJQAHAIAHAEQAKAFALAAQAQAAAYgQIAbAqQgQAOgUAHQgUAIgTAAQgWgBgUgHg");
	this.shape_17.setTransform(616.9,191.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgfBvQgVgJgPgPQgQgQgJgVQgFgPgDgjQAAgRAJgfQAIgWAQgPQAPgQATgJQATgHATgBQAXAAATAJQASAHAMAQQAMAOAGAVQAGATAAAXQAAAQgCALIiGAAQACAMAFAKQAFAJAIAHQAIAGAIADQAJACAMAAQAMAAAMgDQAMgEANgIIAWApQgRAMgWAGQgVAIgUAAQgXgBgVgHgAAsgWQAAgVgJgLQgFgGgGgDQgIgDgKAAQgOAAgMAKQgNAMgDAWIBQAAIAAAAg");
	this.shape_18.setTransform(596,191.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("Ag9DLIALgxQALADAHAAQANAAAFgJQAFgIABgUIAAjhIBBAAIAADgQAAATgEAQQgEAQgKANQgJANgQAGQgOAIgWgBQgYABgPgHgAgDiVQgLgJAAgQQAAgPALgJQAKgLAQAAQASAAAKALQAMAJAAAPQAAAQgMAJQgKALgSgBQgQABgKgLg");
	this.shape_19.setTransform(577.5,190.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgRCbQgQgHgNgOIgBAAIgGAXIg1AAIAAk/IBEAAIAABPIgDAjQAOgMAQgGQANgHAPAAQAVAAAQAIQARAIAMAPQAMAPAFAVQAHAUAAAaQAAAcgIAYQgIAWgNAQQgOAQgRAJQgRAIgTAAQgNAAgPgIgAgTgNQgKAFgJAIIAABdQAIAIAKAEQAJADAJAAQAGAAAIgEQAIgEAFgIQAGgIADgNQADgNAAgRQAAgPgCgMQgCgLgFgGQgEgIgIgDQgHgEgJAAQgKAAgJAFg");
	this.shape_20.setTransform(563.1,186.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgcCXQgNgCgNgFQgMgGgKgHQgLgIgJgKQgJgKgHgNQgHgMgFgOQgFgPgCgQIgDghIADgiQACgRAFgOQAFgOAHgMQAHgMAJgKQAJgKALgHQAKgIAMgFQANgFANgCQAOgDAOAAQAOAAAPADQAOACALAFQANAFALAIQAKAHAJAKQAJAKAIAMQAGAMAFAOQAFAPACAQIADAiIgDAhQgCAQgFAPQgFAOgGAMQgIANgJAKQgJAKgKAIQgLAHgNAGQgLAFgOACQgPADgOAAQgOAAgOgDgAgahZQgMAHgJAMQgIANgFARQgFASAAAWQAAAVAFASQAFASAIANQAJANAMAGQANAHANAAQAOAAANgHQAMgGAJgNQAJgNAEgSQAFgSAAgVQAAgWgFgSQgEgRgJgNQgJgMgMgHQgNgGgOAAQgNAAgNAGg");
	this.shape_21.setTransform(535.8,187.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgzCbQgRgIgNgQQgMgQgGgVQgHgXAAgbQAAgbAIgVQAIgWANgQQANgPARgIQARgIASAAQAQAAAOAGQALAGANAMIgDgjIAAhOIBEAAIAAE/Ig3AAIgFgWIgCAAQgMAMgQAIQgQAIgOAAQgVAAgRgIgAgMgPQgHAEgGAIQgFAGgDAMQgEAMAAAQQAAAQADANQADAMAFAIQAFAIAIAEQAHAEAIAAQAMAAAIgFQAJgFAIgLIAAhbQgIgHgKgEQgJgDgKAAQgGAAgIADg");
	this.shape_22.setTransform(501.1,186.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgfBvQgVgJgPgPQgQgQgJgVQgFgPgDgjQAAgRAJgfQAIgWAQgPQAPgQATgJQATgHATgBQAXAAATAJQASAHAMAQQAMAOAGAVQAGATAAAXQAAAQgCALIiGAAQACAMAFAKQAFAJAIAHQAIAGAIADQAJACAMAAQAMAAAMgDQAMgEANgIIAWApQgRAMgWAGQgVAIgUAAQgXgBgVgHgAAsgWQAAgVgJgLQgFgGgGgDQgIgDgKAAQgOAAgMAKQgNAMgDAWIBQAAIAAAAg");
	this.shape_23.setTransform(478.7,191.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgFCMQgPgHgJgLQgJgMgFgQQgEgPAAgVIAAhaIgfAAIAAgyIAigDIAIg8IA2AAIAAA8IA2AAIAAA1Ig2AAIAABZQAAASAIAKQAHAJAOgBQAKABAMgFIAKAxQgcAIgWAAQgVAAgNgGg");
	this.shape_24.setTransform(460.2,188.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("Ag+BtQgMgGgJgMQgJgLgEgSQgEgQAAgWIAAiLIBDAAIAACDQAAAXAHAKQAGAKAQAAQAKAAAJgGQAIgGALgOIAAiUIBDAAIAADhIg3AAIgFgfIgBAAQgPASgRAJQgPAKgWAAQgSAAgPgHg");
	this.shape_25.setTransform(440.4,191.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgRCbQgQgHgNgOIgCAAIgFAXIg1AAIAAk/IBDAAIAABPIgCAjQAOgMAPgGQAOgHAQAAQAUAAAQAIQARAIAMAPQALAPAGAVQAHAUAAAaQAAAcgIAYQgHAWgOAQQgNAQgSAJQgRAIgTAAQgNAAgPgIgAgTgNQgKAFgKAIIAABdQAJAIAKAEQAJADAIAAQAHAAAIgEQAIgEAGgIQAGgIADgNQACgNAAgRQAAgPgBgMQgDgLgFgGQgEgIgIgDQgHgEgJAAQgKAAgJAFg");
	this.shape_26.setTransform(417.1,186.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AggClIAAjhIBBAAIAADhgAgahoQgLgJAAgQQAAgPALgKQAKgKAQAAQARAAAKAKQALAKAAAPQAAAQgLAJQgLAKgQAAQgQAAgKgKg");
	this.shape_27.setTransform(399.1,186.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AhLB0IAAjhIA3AAIAEAoIADAAQAGgMAHgIQAGgJAIgFQARgMASAAQAQAAALAFIgLA6QgNgEgLAAQgPAAgMAKQgOALgIAVIAACCg");
	this.shape_28.setTransform(387.2,191);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgFCMQgPgHgJgLQgJgMgFgQQgEgPAAgVIAAhaIgfAAIAAgyIAigDIAIg8IA2AAIAAA8IA2AAIAAA1Ig2AAIAABZQAAASAIAKQAHAJAOgBQAKABAMgFIAKAxQgcAIgWAAQgVAAgNgGg");
	this.shape_29.setTransform(369.9,188.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgwBuQgXgJgSgOIAfgqQAPALAOAHQAPAFAOAAQANAAAHgEQAHgGAAgJQAAgKgOgIIgegMQgagKgPgMQgJgIgFgLQgFgLAAgOQAAgPAGgOQAGgNALgIQAMgKAQgFQAQgGASAAQAYABAVAIQARAIASANIgeAoQgNgKgMgFQgMgEgLAAQgLAAgHAEQgGAEAAAKQAAAJANAHIAdAMIAWAJQAMAHAIAFQAJAIAFALQAGAMAAAPQAAAPgGANQgGAOgMAJQgMAKgSAGQgRAFgVABQgWgBgYgIg");
	this.shape_30.setTransform(352.9,191.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AggClIAAjhIBBAAIAADhgAgahoQgLgJAAgQQAAgPALgKQAKgKAQAAQARAAAKAKQALAKAAAPQAAAQgLAJQgLAKgQAAQgQAAgKgKg");
	this.shape_31.setTransform(338.7,186.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AhzCVIAAkpIBTAAQAYAAAkAJQAOAEAMAHQAMAHAKAJQAJAJAIALQAIAMAFAOQAFAOADAQQACARABATQgBARgCARQgDARgFAOQgFAOgIAMQgHAMgKAJQgJAJgLAHQgNAHgNAFIgcAHIgdACgAgwBeIANAAQAUAAAOgFQAOgFALgLQALgMAGgSQAGgTAAgYQAAgagGgTQgGgRgLgLQgLgLgOgFQgOgEgUAAIgNAAg");
	this.shape_32.setTransform(320.7,187.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgKALQgEgEAAgHQAAgFAEgFQAFgFAFAAQAGAAAFAFQAEAFAAAFQAAAHgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape_33.setTransform(751,289.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgUAyQgKgEgJgHIAMgPQAIAFAGAEQAIADAFAAQAIgBAEgDQAEgEABgFQgBgFgGgFIgOgGIgKgFIgJgEQgFgEgDgEQgCgGAAgGQAAgHACgFQADgGAFgEQAFgFAHgCQAHgCAHAAQAKAAAJADQAIAEAIAFIgMAPQgGgEgFgCQgGgDgGABQgFAAgEACQgEADAAAGQAAAFAGAEIAOAGIAKAEIAKAEQAEAFADAFQADAFgBAHQABAGgDAHQgDAGgFAEQgFAEgHADQgIACgJAAQgJAAgLgEg");
	this.shape_34.setTransform(744,286.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AguBJIAAiPIAUAAIACALIAAAAQAHgGAJgDQAIgEAGAAQAJAAAJADQAHAEAFAHQAFAHADAKQADAKAAAMQAAANgEAIQgDALgGAHQgHAHgIAEQgIAEgJAAQgEAAgHgDQgGgDgIgGIABASIAAAggAgKgxQgFADgHAFIAAAvQAGAFAGACQAEACAGAAQACAAAFgDQAEgCAEgEQADgFACgFQABgHAAgIIgBgOQgBgGgCgEQgEgFgEgCQgEgCgFAAQgEAAgGADg");
	this.shape_35.setTransform(734.4,288);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AguBJIAAiPIAUAAIACALIABAAQAHgGAHgDQAJgEAGAAQAJAAAIADQAIAEAFAHQAFAHADAKQADAKAAAMQAAANgEAIQgDALgHAHQgGAHgIAEQgIAEgIAAQgGAAgGgDQgHgDgGgGIABASIAAAggAgKgxQgGADgFAFIAAAvQAFAFAFACQAFACAFAAQADAAAFgDQAFgCADgEQADgFACgFQABgHABgIIgBgOQgCgGgDgEQgCgFgFgCQgEgCgFAAQgFAAgFADg");
	this.shape_36.setTransform(723,288);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgXA0QgFgDgFgEQgEgDgCgGQgCgGAAgGQAAgJADgGQAEgHAHgCQAIgFALgDQAKgDAQgCQAAgJgEgFIgGgFQgEgBgEAAQgGgBgIADQgGADgIAFIgJgRQAKgFAJgEQAMgEAKAAQAJAAAIADQAHADAFAFQAFAGACAJQACAIAAALIAAA8IgUAAIgBgMIgBAAQgIAGgHAEQgHAEgIAAQgHAAgGgCgAAAADQgFACgEAEQgFACgCAEQgBADAAADQAAAIAEADQAEADAGAAQAEAAAGgDQAFgCAGgGIAAgYIgSADg");
	this.shape_37.setTransform(711.5,286.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgNAzQgJgFgHgHQgHgGgEgLQgEgKAAgMQAAgLAEgLQAEgJAHgIQAGgGAKgFQAIgDAHAAQALAAAIADQAHAEAGAGQAFAHADAJQADAKAAAKIgBAKIhAAAQAAAHAEAFQACAGAEADQAEAEAFACQADACAHAAQAGAAAHgCQAFgCAGgEIAIAQQgIAFgJADQgJADgKAAQgJAAgJgDgAAYgIQAAgGgCgFQgBgFgCgDQgDgEgEgCQgEgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFQgCAFgCAGIAtAAIAAAAg");
	this.shape_38.setTransform(697.6,286.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AAyA1IAAg8QAAgNgFgGQgDgFgJAAQgEAAgGADQgGAEgFAGIAABHIgXAAIAAg8QAAgNgDgGQgFgFgIAAQgFAAgFADQgGAEgFAGIAABHIgZAAIAAhmIAUAAIACAOIABAAQAHgIAHgEQAIgFAJAAIAKABIAJAEQAEAFAEAJQAJgJAHgEIAIgEQAFgCAFAAQAIAAAGADQAGADAEAFQAEAFACAIQACAHAAAKIAABAg");
	this.shape_39.setTransform(683.9,286);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgLBLIAAhnIAXAAIAABngAgJgxQgFgFAAgFQAAgGAFgFQAEgEAFAAQAGAAAEAEQAFAFAAAGQAAAFgFAFQgEADgGAAQgFAAgEgDg");
	this.shape_40.setTransform(672.6,283.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgBBBQgGgEgEgEQgEgFgBgIQgCgGAAgIIAAgxIgPAAIAAgSIAQgBIADgcIASAAIAAAcIAbAAIAAATIgbAAIAAAxQAAAIAEAFQAEAEAHABQAFgBAGgCIAEATQgLADgKAAQgJAAgFgCg");
	this.shape_41.setTransform(666.6,284.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgEBJQgFgCgCgDQgDgEgBgFQgCgGAAgHIAAh4IAXAAIAAB5QAAAJAFgBIAEAAIADASQgFACgIAAQgFAAgEgCg");
	this.shape_42.setTransform(657.1,284);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgXA0QgFgDgFgEQgEgDgCgGQgCgGAAgGQAAgJADgGQAEgHAHgCQAIgFALgDQAKgDAQgCQAAgJgEgFIgGgFQgEgBgEAAQgGgBgIADQgGADgIAFIgJgRQAKgFAJgEQAMgEAKAAQAJAAAIADQAHADAFAFQAFAGACAJQACAIAAALIAAA8IgUAAIgBgMIgBAAQgIAGgHAEQgHAEgIAAQgHAAgGgCgAAAADQgFACgEAEQgFACgCAEQgBADAAADQAAAIAEADQAEADAGAAQAEAAAGgDQAFgCAGgGIAAgYIgSADg");
	this.shape_43.setTransform(648.6,286.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgMAzQgKgFgHgHQgHgGgEgLQgEgKAAgMQAAgLAEgLQAEgJAHgIQAHgGAJgFQAIgDAHAAQALAAAIADQAHAEAGAGQAFAHADAJQADAKAAAKIgBAKIhAAAQAAAHADAFQADAGAEADQAEAEAFACQAEACAFAAQAHAAAHgCQAFgCAGgEIAIAQQgHAFgKADQgJADgKAAQgJAAgIgDgAAYgIQAAgGgBgFQgBgFgEgDQgCgEgEgCQgEgBgFAAQgDAAgEABQgEACgDAEQgEADgCAFQgCAFgBAGIAsAAIAAAAg");
	this.shape_44.setTransform(638.4,286.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AAYBFIgdg2IgVAAIAAA2IgYAAIAAiJIAvAAQAJAAAJACQAJACAHAFQAHAFAEAIQADAIAAALQAAAIgCAHQgCAGgDAFQgDADgGADQgFAEgGACIAhA6gAgagDIAUAAQAGAAAFgCQAFgBAEgDQADgDACgEQACgFABgGQgBgGgCgEQgCgEgDgCQgEgDgFgBIgLgBIgUAAg");
	this.shape_45.setTransform(627.9,284.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#999999").s().p("AgOAUQAIgFAFgHQADgGABgGIgDAAQgDAAgEgEQgDgCAAgHQAAgFADgEQAFgDADAAQAGABAFAFQADAGAAAJQAAAGgBAFIgGALQgEAFgEAEQgEAEgHADg");
	this.shape_46.setTransform(615,291.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#999999").s().p("AAABAQgFgCgEgFQgDgEgBgHQgCgGAAgIIAAg3IgPAAIAAgNIAPgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QAAAKAEAEQADAGAJAAQAEAAAIgDIAEANQgMAEgHAAQgJAAgEgDg");
	this.shape_47.setTransform(609.5,284.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#999999").s().p("AAXA0IAAg9IgBgMIgDgJQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGADgIAJIAABIIgSAAIAAhlIAPAAIABAPIABAAQAIgIAHgEIAIgEIAJgBQAIAAAGACQAGADAEAFQAEAFACAIQACAHAAAKIAAA/g");
	this.shape_48.setTransform(600.6,286);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgEIAGALQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_49.setTransform(590.1,286.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#999999").s().p("AA1A0IAAg9IgBgMQgBgFgCgEQgDgDgDgCQgEgBgFAAQgGAAgGAEQgGAEgIAIIAABIIgPAAIAAg9IgBgMIgDgJQgDgDgEgCQgEgBgFAAQgFAAgGAEQgHAEgHAIIAABIIgSAAIAAhlIAPAAIABAPIABAAQAHgIAIgEQAIgFAJAAQAGAAAFABQAEABAEADQAEAFAEAJQAIgJAIgFQAIgFAKAAQAHAAAGACQAGADAEAFQAEAFACAIQACAHgBAKIAAA/g");
	this.shape_50.setTransform(576.7,286);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgEIAGALQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_51.setTransform(563.1,286.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#999999").s().p("AgVBKQgHgCgGgDQgGgEgDgFQgDgFAAgHQAAgGAEgHQAEgGAHgEIAAgBQgEgDgCgEQgDgEAAgGQAAgFAEgEQADgFAEgDIAAgBQgFgEgEgHQgEgHAAgKQAAgIADgHQADgGAFgFQAGgFAHgDQAHgCAHAAQAGAAAHACIAkAAIAAAOIgVAAQAEADACAGQADAGAAAGQgBAIgDAHQgCAHgGAEQgEAFgIADQgHACgGAAQgHAAgIgDQgGAFAAAEQAAAGADADQAFADAKAAIARAAIARABQAGACAEADQAFACADAGQACAEAAAHQAAAGgEAHQgDAGgHAGQgIAEgIADQgLADgKAAQgJAAgIgCgAgcAlQgDAEAAAFQAAAEADADIAFAGQAEACAFABQAGACAHAAQAGAAAFgCQAGgBAFgDIAHgHQACgEAAgEQAAgHgFgDQgGgDgKAAIgQAAQgHAAgGgBQgFAEgDAEgAgMg8QgEABgDADQgDADgCAFQgBAEAAAFQAAAGABAFQACAFADACQADAEAEACQAEABAEAAQAEAAADgBQAEgCADgEQADgCACgFQABgFABgGQgBgFgBgEQgCgFgDgDQgDgDgEgBQgDgDgEAAQgEAAgEADg");
	this.shape_52.setTransform(553.4,288.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_53.setTransform(542.7,286.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#999999").s().p("AAXA0IAAg9IgBgMIgDgJQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGADgIAJIAABIIgSAAIAAhlIAPAAIABAPIABAAQAIgIAHgEIAIgEIAJgBQAIAAAGACQAGADAEAFQAEAFACAIQACAHAAAKIAAA/g");
	this.shape_54.setTransform(532.3,286);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_55.setTransform(521.4,286.2);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#999999").s().p("AA1A0IAAg9IgBgMQgBgFgDgEQgCgDgDgCQgEgBgFAAQgGAAgGAEQgHAEgGAIIAABIIgQAAIAAg9IgBgMIgEgJQgCgDgEgCQgEgBgEAAQgGAAgHAEQgGAEgHAIIAABIIgRAAIAAhlIAOAAIACAPIAAAAQAHgIAHgEQAJgFAJAAQAFAAAGABQAEABADADQAFAFAEAJQAIgJAHgFQAKgFAIAAQAIAAAGACQAGADAEAFQAEAFACAIQABAHABAKIAAA/g");
	this.shape_56.setTransform(508,286);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgEIAGALQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_57.setTransform(490.7,286.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#999999").s().p("AAABAQgFgCgEgFQgDgEgCgHQgBgGAAgIIAAg3IgPAAIAAgNIAPgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QABAKADAEQADAGAJAAQAEAAAIgDIAEANQgMAEgHAAQgJAAgEgDg");
	this.shape_58.setTransform(482.5,284.8);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_59.setTransform(473.8,286.2);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#999999").s().p("AAABAQgFgCgEgFQgDgEgBgHQgCgGAAgIIAAg3IgPAAIAAgNIAQgBIACgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QAAAKAEAEQAEAGAIAAQAFAAAHgDIAEANQgMAEgHAAQgJAAgEgDg");
	this.shape_60.setTransform(465.6,284.8);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#999999").s().p("AgMBGIgNgEQgGgDgFgEQgGgDgEgFIAKgMQAIAHAKAFQAKAFAIAAQAHAAAGgBQAFgCAEgDQADgDACgFQACgDAAgGQAAgEgCgFQgBgDgDgDQgEgEgNgFIgRgJIgKgDQgGgEgDgEQgFgEgCgGQgDgFAAgIQAAgIAEgGQACgHAHgFQAFgFAIgDQAIgDAIAAQAIAAAPAFQAKAFAIAHIgJAMQgHgGgIgDQgIgEgJAAQgEAAgFABQgFACgDADQgDACgCADQgCAFAAAEQAAAFACAEQABADAEADQAFAEAKAEIATAJIALAEIAKAHQADAFACAGQACAFAAAIQAAAIgDAIQgDAGgGAGQgGAFgJADQgJADgLAAIgMgBg");
	this.shape_61.setTransform(456.9,284.4);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#999999").s().p("AgPAUQAJgFAGgHQACgGAAgGIgBAAQgEAAgDgEQgEgCAAgHQAAgFAEgEQADgDAEABQAHAAADAFQAEAGABAJQgBAGgCAFIgFALQgEAFgEAEQgEAEgHADg");
	this.shape_62.setTransform(845.4,263.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_63.setTransform(837.7,257.4);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#999999").s().p("AAABAQgFgCgEgFQgDgEgBgHQgCgGAAgIIAAg3IgPAAIAAgNIAPgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QAAAKAEAEQADAGAJAAQAEAAAIgDIAEANQgMAEgHAAQgJAAgEgDg");
	this.shape_64.setTransform(829.6,256);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_65.setTransform(820.8,257.4);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#999999").s().p("AgTBJQgIgEgFgHQgGgHgDgKQgDgKAAgNQAAgMAEgKQADgIAHgHQAGgHAIgEQAIgEAIAAQAHAAAHADQAGADAIAGIgBgSIAAgnIASAAIAACVIgPAAIgBgMIgBAAQgHAGgHAEQgJAEgGAAQgKAAgIgDgAgIgMQgFACgEAGQgEAEgCAGQgDAIAAAIQAAAJACAIQACAHAEAFQADAFAGADQAFADAFAAQAHAAAGgEQAHgDAGgIIAAgzQgGgGgHgDQgGgCgGAAQgEAAgGADg");
	this.shape_66.setTransform(809.8,255.1);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#999999").s().p("AgpBHIAEgOIAHACQAFAAADgCIAGgFQAGgFADgKIADgIIgqhlIASAAIAVA5IAIAbIACAAIAIgbIATg5IAQAAIgnBtQgCAIgEAGQgBAHgEAFQgGAFgFACQgHADgHAAQgHAAgFgCg");
	this.shape_67.setTransform(796.3,259.6);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_68.setTransform(786.3,257.4);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#999999").s().p("AAWAzIgPg2IgHgdIAAAAIgGAeIgPA1IgUAAIgdhlIASAAIAQA5IAGAdIAAAAIAHgdIAQg5IAQAAIAQA5IAHAdIABAAIAGgdIAPg5IARAAIgcBlg");
	this.shape_69.setTransform(773.9,257.4);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#999999").s().p("AgXAGIAAgLIAvAAIAAALg");
	this.shape_70.setTransform(763.6,257.2);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgFIAGAMQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_71.setTransform(755.6,257.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#999999").s().p("AAXA0IAAg9IgBgMIgDgJQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGADgIAJIAABIIgSAAIAAhlIAPAAIABAPIABAAQAIgIAHgEIAIgEIAJgBQAIAAAGACQAGADAEAFQAEAFACAIQACAHAAAKIAAA/g");
	this.shape_72.setTransform(745.2,257.2);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#999999").s().p("AgLBGQgGgBgFgCIgLgHIgIgIQgFgFgCgGIgGgMIgDgOIgBgPQAAgLAEgSIAGgMIAHgKIAIgIQAFgFAGgCIALgDIALgCIAMACIALADQAGACAEAFQAFADAEAFQAEAEADAGQAEAGABAGQAFASAAALIgBAPIgEAOQgBAHgEAFQgDAGgEAFIgJAIIgKAHQgFACgGABQgGABgGAAQgFAAgGgBgAgQgzQgHAEgGAHQgFAIgDAKQgDAKAAAMQAAAMADALQADAKAFAHQAGAIAHAEQAIAEAIAAQAJAAAHgEQAIgEAGgIQAFgHADgKQADgLAAgMQAAgMgDgKQgDgKgFgIQgGgHgIgEQgHgEgJAAQgIAAgIAEg");
	this.shape_73.setTransform(732.9,255.6);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#999999").s().p("AgOAUQAIgFAFgHQAEgGAAgGIgCAAQgEAAgDgEQgEgCAAgHQAAgFAEgEQAEgDADABQAGAAAFAFQADAGAAAJQAAAGgCAFIgFALQgDAFgFAEQgEAEgHADg");
	this.shape_74.setTransform(716.4,263.1);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#999999").s().p("AgUBKQgJgCgFgDQgGgEgDgFQgDgFAAgHQAAgGAEgHQAEgGAHgEIAAgBQgEgDgCgEQgDgEAAgGQAAgFAEgEQADgFAEgDIAAgBQgGgEgDgHQgEgHAAgJQAAgJADgHQADgGAGgFQAFgFAHgDQAHgCAIAAQAGAAAGACIAkAAIAAAOIgVAAQAEADACAGQACAGABAGQAAAIgEAHQgDAHgEAEQgFAFgIADQgGACgGAAQgIAAgIgDQgGAFgBAFQAAAFAFADQAEADAKAAIARAAIAQABQAIACADADQAGACABAGQADAEAAAGQAAAIgEAGQgDAGgHAGQgHAEgJADQgLADgJAAQgKAAgHgCgAgcAlQgCAEAAAFQAAAEACADIAFAGQAEACAFABQAGACAHAAQAGAAAFgCQAHgBAEgDIAGgHQADgEAAgEQAAgHgFgDQgGgDgKAAIgQAAQgHAAgGgBQgGAEgCAEgAgMg8QgEABgDADQgDADgCAFQgBAEAAAGQAAAFABAFQACAFADACQAEAEADACQAEABAFAAQADAAADgBQAEgCADgEQADgCACgFQABgFABgFQgBgGgBgEQgCgFgDgDQgDgDgEgBQgDgDgDAAQgFAAgEADg");
	this.shape_75.setTransform(709.3,259.6);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#999999").s().p("AAXA0IAAg9IgBgMIgDgJQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGADgIAJIAABIIgSAAIAAhlIAPAAIABAPIABAAQAIgIAHgEIAIgEIAJgBQAIAAAGACQAGADAEAFQAEAFACAIQACAHAAAKIAAA/g");
	this.shape_76.setTransform(698.5,257.2);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#999999").s().p("AgHBJIAAhlIAPAAIAABlgAgHg1QgEgDAAgFQAAgFAEgDQADgDAEAAQAFAAADADQAEADAAAFQAAAFgEADQgDAEgFAAQgEAAgDgEg");
	this.shape_77.setTransform(690.6,255.2);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#999999").s().p("AgVBKQgIgCgFgDQgGgEgDgFQgDgFAAgHQAAgGAEgHQAEgGAHgEIAAgBQgEgDgDgEQgCgEAAgGQAAgFADgEQADgFAFgDIAAgBQgGgEgDgHQgEgHAAgJQAAgJADgHQADgGAGgFQAEgFAIgDQAHgCAIAAQAFAAAIACIAjAAIAAAOIgVAAQADADADAGQADAGgBAGQAAAIgCAHQgDAHgFAEQgGAFgGADQgIACgFAAQgJAAgHgDQgHAFAAAFQABAFAEADQAEADAKAAIASAAIAPABQAHACAFADQAEACACAGQADAEAAAGQAAAIgEAGQgEAGgGAGQgIAEgJADQgJADgKAAQgKAAgIgCgAgcAlQgDAEABAFQAAAEABADIAGAGQAEACAGABQAFACAHAAQAFAAAHgCQAFgBAFgDIAHgHQACgEAAgEQAAgHgGgDQgEgDgLAAIgPAAQgIAAgGgBQgGAEgCAEgAgMg8QgEABgDADQgDADgBAFQgCAEAAAGQAAAFACAFQABAFADACQADAEAEACQAEABAFAAQADAAADgBQAEgCADgEQADgCACgFQABgFAAgFQAAgGgBgEQgCgFgDgDQgDgDgEgBQgDgDgDAAQgFAAgEADg");
	this.shape_78.setTransform(683.5,259.6);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#999999").s().p("AgUBKQgJgCgFgDQgGgEgDgFQgDgFAAgHQAAgGAEgHQAEgGAHgEIAAgBQgEgDgCgEQgDgEAAgGQAAgFADgEQADgFAFgDIAAgBQgFgEgEgHQgEgHAAgJQAAgJADgHQADgGAGgFQAEgFAIgDQAHgCAIAAQAFAAAHACIAkAAIAAAOIgVAAQAEADACAGQACAGABAGQAAAIgDAHQgEAHgEAEQgGAFgHADQgHACgFAAQgJAAgHgDQgHAFAAAFQAAAFAFADQAEADAKAAIARAAIAQABQAIACADADQAGACABAGQADAEAAAGQAAAIgEAGQgEAGgGAGQgHAEgKADQgKADgJAAQgKAAgHgCgAgcAlQgCAEAAAFQAAAEACADIAFAGQAEACAGABQAFACAHAAQAGAAAFgCQAHgBAEgDIAGgHQADgEAAgEQAAgHgGgDQgEgDgLAAIgQAAQgHAAgGgBQgFAEgDAEgAgMg8QgEABgDADQgDADgCAFQgBAEAAAGQAAAFABAFQACAFADACQAEAEADACQAEABAFAAQADAAADgBQAEgCADgEQADgCACgFQACgFgBgFQABgGgCgEQgCgFgDgDQgDgDgEgBQgDgDgDAAQgFAAgEADg");
	this.shape_79.setTransform(673.4,259.6);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#999999").s().p("AgWAyQgGgDgEgFQgEgFgBgIQgDgHAAgKIAAg/IASAAIAAA9IABAMQABAFADAEQACADAEACQADABAGAAQAFAAAGgEQAHgEAHgJIAAhHIASAAIAABlIgPAAIgBgQIgBAAQgIAJgIAEQgDADgFABIgIABQgIAAgGgCg");
	this.shape_80.setTransform(662.4,257.5);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#999999").s().p("AgNBJQgHgDgIgGIAAAAIgCAKIgNAAIAAiVIARAAIAAApIAAATQAHgHAHgEQAKgEAFAAQALAAAHAEQAIAEAFAGQAFAHADAJQADAJAAAMQAAAMgEALQgDAKgHAIQgGAHgIAEQgIADgJAAQgFAAgIgDgAgMgMQgHAEgHAHIAAA0QAGAFAHADQAGADAGAAQAEAAAGgDQAFgDAEgFQAEgGACgHQADgIAAgJQAAgJgCgHQgBgFgEgFQgDgFgFgCQgGgDgGAAQgFAAgHADg");
	this.shape_81.setTransform(651.8,255.1);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgFIAGAMQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_82.setTransform(640.8,257.4);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#999999").s().p("AgTBJQgIgEgFgHQgGgHgDgKQgDgKAAgNQAAgMAEgKQADgIAHgHQAGgHAIgEQAIgEAIAAQAHAAAHADQAGADAIAGIgBgSIAAgnIASAAIAACVIgPAAIgBgMIgBAAQgHAGgHAEQgJAEgGAAQgKAAgIgDgAgIgMQgFACgEAGQgEAEgCAGQgDAIAAAIQAAAJACAIQACAHAEAFQADAFAGADQAFADAFAAQAHAAAGgEQAHgDAGgIIAAgzQgGgGgHgDQgGgCgGAAQgEAAgGADg");
	this.shape_83.setTransform(629.8,255.1);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#999999").s().p("AgDBLQgDgCgDgDQgEgFAAgMIAAiAIAQAAIAACBQAAAIAEAAIAEgBIADAOQgEABgGAAQgEAAgDgBg");
	this.shape_84.setTransform(618.9,255.1);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgFIAGAMQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_85.setTransform(611.1,257.4);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#999999").s().p("AgIAzIgmhlIASAAIAUA4IAIAfIABAAIAJgfIATg4IASAAIglBlg");
	this.shape_86.setTransform(601.4,257.4);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_87.setTransform(591.4,257.4);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#999999").s().p("AgbA0IAAhlIAPAAIABATIABAAQAFgKAGgGQAHgFAJAAQAGAAAFACIgDAPQgGgCgEAAQgIAAgGAGIgFAHIgFALIAABAg");
	this.shape_88.setTransform(583.9,257.2);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#999999").s().p("AAABAQgFgCgEgFQgDgEgBgHQgCgGAAgIIAAg3IgPAAIAAgNIAQgBIACgdIANAAIAAAdIAbAAIAAAOIgbAAIAAA4QAAAKADAEQAEAGAIAAQAFAAAHgDIADANQgLAEgHAAQgJAAgEgDg");
	this.shape_89.setTransform(576.4,256);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#999999").s().p("AgXAGIAAgLIAvAAIAAALg");
	this.shape_90.setTransform(570,257.2);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgFIAGAMQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_91.setTransform(562,257.4);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#999999").s().p("AA1A0IAAg9IgBgMQgBgFgDgEQgCgDgDgCQgEgBgFAAQgGAAgGAEQgHAEgGAIIAABIIgQAAIAAg9IgBgMIgDgJQgDgDgEgCQgEgBgEAAQgGAAgGAEQgHAEgHAIIAABIIgSAAIAAhlIAPAAIACAPIAAAAQAHgIAIgEQAIgFAJAAQAFAAAGABQAEABAEADQAEAFAEAJQAIgJAHgFQAKgFAIAAQAIAAAGACQAGADAEAFQAEAFACAIQABAHABAKIAAA/g");
	this.shape_92.setTransform(548.6,257.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#999999").s().p("AgHBJIAAhlIAPAAIAABlgAgHg1QgEgDAAgFQAAgFAEgDQADgDAEAAQAFAAADADQAEADAAAFQAAAFgEADQgDAEgFAAQgEAAgDgEg");
	this.shape_93.setTransform(537.6,255.2);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#999999").s().p("AgHBFIAAh6IgqAAIAAgPIBjAAIAAAPIgqAAIAAB6g");
	this.shape_94.setTransform(529.9,255.6);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#999999").s().p("AgPAUQAJgFAGgHQACgGAAgGIgCAAQgDAAgEgEQgDgCAAgHQAAgFADgEQAEgDAEABQAGAAAEAFQAFAGAAAJQAAAGgCAFIgGALQgEAFgEAEQgEAEgGADg");
	this.shape_95.setTransform(514.8,263.1);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#999999").s().p("AgTAyQgKgFgHgFIAIgMQAIAFAGAEQAIADAGAAQALAAAFgFQAFgEAAgHQAAgEgDgDQgBgDgDgCQgGgEgJgDIgLgFIgJgEQgFgDgCgFQgDgFAAgGQAAgHACgFQADgFAEgEQAEgEAHgCQAHgCAGgBQAJAAAJAEQAIADAGAFIgJALQgFgFgFgCQgHgCgGAAQgHAAgFAEQgFAFAAAGQAAAGAHAFQAEACAKAFIALAEIAKAEQAFAEACAFQADAFAAAHQAAAGgCAFQgDAHgEADQgFAFgHACQgIACgIAAQgJAAgKgDg");
	this.shape_96.setTransform(508.3,257.4);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#999999").s().p("AgMAyQgJgEgHgGQgGgIgEgKQgEgKAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgEAHAAQAKAAAIAEQAHADAGAHQAFAGADAJQACAJAAALIAAAIIhEAAQABAHACAIQADAGAEAFQAFAFAGACQAEACAIABQAGAAAHgCQAGgCAGgFIAGAMQgHAFgIACQgJADgKAAQgIAAgJgDgAAcgGQAAgIgCgGQgBgGgEgEQgDgEgFgDQgEgCgGAAQgEAAgFACQgFACgEAFQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_97.setTransform(499.2,257.4);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#999999").s().p("AAABAQgFgCgDgFQgEgEgCgHQgBgGAAgIIAAg3IgQAAIAAgNIAQgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QABAKADAEQADAGAKAAQADAAAIgDIAEANQgMAEgIAAQgIAAgEgDg");
	this.shape_98.setTransform(491,256);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#999999").s().p("AgVAzQgFgCgEgDQgEgEgDgFQgCgGAAgHQAAgIAEgGQAEgHAHgDQAIgEAMgEQAKgDAQgBIgBgKIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJADQgGADgIAFIgGgMQAIgGAJgDIALgDIAKgCQAJABAHADQAHADAEAFQAFAGACAHQACAIAAAKIAAA9IgPAAIgBgMIgBAAQgIAGgIAEQgHAFgJgBQgGAAgGgCgAABABQgHACgGADQgFAEgCAEQgDAEAAAFQAAAIAFAEQAFAFAIAAQAFgBAHgDQAHgDAHgIIAAgaQgMABgJABg");
	this.shape_99.setTransform(482.3,257.4);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#999999").s().p("AgTBJQgIgEgFgHQgGgHgDgKQgDgKAAgNQAAgMAEgKQADgIAHgHQAGgHAIgEQAIgEAIAAQAHAAAHADQAGADAIAGIgBgSIAAgnIASAAIAACVIgPAAIgBgMIgBAAQgHAGgHAEQgJAEgGAAQgKAAgIgDgAgIgMQgFACgEAGQgEAEgCAGQgDAIAAAIQAAAJACAIQACAHAEAFQADAFAGADQAFADAFAAQAHAAAGgEQAHgDAGgIIAAgzQgGgGgHgDQgGgCgGAAQgEAAgGADg");
	this.shape_100.setTransform(471.3,255.1);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#999999").s().p("AgsBKIAAiRIAPAAIABANIABAAQAHgHAIgEQAKgEAGAAQAJAAAJADQAHAFAFAGQAFAHADAKQACAKAAAMQAAAMgDAJQgEAKgGAHQgGAHgIAFQgIADgJAAQgFAAgHgDQgIgDgHgGIABASIAAAjgAgMg3QgHAEgHAGIAAA0QAGAGAIADQAFACAGAAQAEAAAFgCQAGgDAEgGQAEgFACgFQACgIAAgJQAAgJgBgHQgCgHgDgFQgDgFgFgCQgFgDgHAAQgFAAgHADg");
	this.shape_101.setTransform(460.8,259.4);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#999999").s().p("AgWAyQgGgDgEgFQgEgFgCgIQgCgHAAgKIAAg/IASAAIAAA9IABAMQABAFADAEQACADADACQAEABAFAAQAGAAAHgEQAFgEAIgJIAAhHIARAAIAABlIgOAAIgCgQIAAAAQgIAJgHAEQgEADgFABIgIABQgIAAgGgCg");
	this.shape_102.setTransform(449.3,257.5);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#999999").s().p("AgKAyQgJgEgGgGQgHgIgDgKQgFgKAAgMQABgLAEgKQADgKAIgHQAGgHAKgEQAIgEAJAAQAIAAAJAEQAHADAFAGIgIALQgFgFgFgCQgFgCgGAAQgHAAgEACQgGAEgEAFQgFAFgCAIQgCAHgBAHQABAIACAIQADAHADAFQAFAGAFADQAFACAHAAQAGAAAHgDQAFgCAFgFIAIALQgGAGgJAEQgJADgJAAQgIAAgJgDg");
	this.shape_103.setTransform(435.8,257.4);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#999999").s().p("AgHBJIAAhlIAPAAIAABlgAgHg1QgEgDAAgFQAAgFAEgDQADgDAEAAQAFAAADADQAEADAAAFQAAAFgEADQgDAEgFAAQgEAAgDgEg");
	this.shape_104.setTransform(428.7,255.2);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#999999").s().p("AAABAQgFgCgDgFQgEgEgCgHQgBgGAAgIIAAg3IgPAAIAAgNIAPgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QABAKADAEQADAGAJAAQAEAAAIgDIAEANQgMAEgHAAQgJAAgEgDg");
	this.shape_105.setTransform(423.1,256);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#999999").s().p("AgTAyQgKgFgIgFIAJgMQAHAFAHAEQAIADAHAAQAKAAAEgFQAGgEAAgHQAAgEgCgDQgCgDgEgCQgEgEgKgDIgLgFIgKgEQgEgDgDgFQgDgFAAgGQABgHACgFQACgFAFgEQAEgEAHgCQAHgCAGgBQAJAAAJAEQAIADAGAFIgIALQgGgFgGgCQgFgCgHAAQgHAAgFAEQgFAFAAAGQAAAGAIAFQADACAKAFIAMAEIAKAEQAEAEADAFQADAFAAAHQgBAGgCAFQgCAHgFADQgFAFgHACQgIACgIAAQgJAAgKgDg");
	this.shape_106.setTransform(415.5,257.4);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#999999").s().p("AgHBJIAAhlIAPAAIAABlgAgHg1QgEgDAAgFQAAgFAEgDQADgDAEAAQAFAAADADQAEADAAAFQAAAFgEADQgDAEgFAAQgEAAgDgEg");
	this.shape_107.setTransform(409.1,255.2);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#999999").s().p("AA1A0IAAg9IgBgMQgBgFgDgEQgCgDgDgCQgEgBgFAAQgGAAgGAEQgGAEgIAIIAABIIgPAAIAAg9IgBgMIgDgJQgDgDgEgCQgEgBgEAAQgGAAgGAEQgHAEgHAIIAABIIgSAAIAAhlIAPAAIACAPIAAAAQAHgIAIgEQAIgFAJAAQAFAAAGABQAEABAEADQAEAFAEAJQAIgJAHgFQAKgFAIAAQAIAAAGACQAGADAEAFQAEAFACAIQABAHABAKIAAA/g");
	this.shape_108.setTransform(398.3,257.2);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#999999").s().p("AgHBJIAAhlIAPAAIAABlgAgHg1QgEgDAAgFQAAgFAEgDQADgDAEAAQAFAAADADQAEADAAAFQAAAFgEADQgDAEgFAAQgEAAgDgEg");
	this.shape_109.setTransform(387.4,255.2);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#999999").s().p("AAABAQgFgCgDgFQgEgEgCgHQgBgGAAgIIAAg3IgQAAIAAgNIAQgBIADgdIANAAIAAAdIAbAAIAAAOIgbAAIAAA4QgBAKAEAEQADAGAKAAQAEAAAHgDIADANQgLAEgIAAQgIAAgEgDg");
	this.shape_110.setTransform(381.9,256);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#999999").s().p("AgsBKIAAiRIAPAAIACANIAAAAQAHgHAJgEQAIgEAHAAQAKAAAIADQAHAFAFAGQAFAHADAKQADAKgBAMQAAAMgDAJQgDAKgHAHQgGAHgIAFQgIADgJAAQgFAAgHgDQgHgDgHgGIAAASIAAAjgAgMg3QgGAEgIAGIAAA0QAGAGAIADQAGACAFAAQAFAAAEgCQAGgDAEgGQAEgFADgFQABgIAAgJQABgJgCgHQgCgHgDgFQgDgFgFgCQgFgDgHAAQgFAAgHADg");
	this.shape_111.setTransform(373.2,259.4);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#999999").s().p("AgLBGQgGgBgFgCIgLgHIgIgIQgFgFgDgGIgFgMIgDgOIgBgPQAAgLAEgSIAFgMIAIgKIAIgIQAFgFAGgCIALgDIALgCIAMACIALADQAGACAEAFQAGADADAFQAEAEADAGQAEAGACAGQAEASAAALIgCAPIgCAOQgCAHgEAFQgDAGgEAFIgJAIIgKAHQgFACgGABQgGABgGAAQgFAAgGgBgAgPgzQgIAEgGAHQgFAIgDAKQgDAKAAAMQAAAMADALQADAKAFAHQAGAIAIAEQAHAEAIAAQAIAAAIgEQAIgEAGgIQAFgHADgKQACgLAAgMQAAgMgCgKQgDgKgFgIQgGgHgIgEQgIgEgIAAQgIAAgHAEg");
	this.shape_112.setTransform(360.5,255.6);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#999999").s().p("AgPATQAJgEAGgGQACgHAAgHIgBAAQgEAAgEgCQgDgEAAgFQAAgGADgDQAEgDAEAAQAGgBAEAGQAEAGABAJQAAAGgDAFIgFALQgEAFgEAEQgEAEgGACg");
	this.shape_113.setTransform(890.9,234.4);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#999999").s().p("AgVBKQgHgCgGgDQgGgEgDgFQgDgFAAgHQAAgGAEgHQAEgFAHgFIAAgBQgEgDgDgEQgCgEAAgFQAAgGADgEQAEgFAEgDIAAAAQgGgGgDgGQgEgIAAgIQAAgJADgGQADgIAFgEQAFgFAIgCQAHgDAHAAQAHAAAHADIAjAAIAAANIgVAAQADADADAGQADAGgBAGQAAAIgCAHQgEAHgFAEQgEAFgHACQgHADgHAAQgIAAgHgEQgHAGABAFQAAAFADACQAFAEAKAAIASAAIAQABQAGACAFACQAEAEADAEQACAFAAAHQAAAGgEAHQgDAGgHAFQgIAFgJADQgJADgLAAQgJAAgIgCgAgcAlQgCAEgBAFQAAAEACAEIAGAFQAEACAGABQAFACAHAAQAFAAAHgCQAFgBAFgEIAHgGQACgEAAgEQAAgHgGgDQgEgDgLAAIgPAAQgIAAgGgCQgGAFgCAEgAgMg9QgEACgDADQgDADgBAEQgCAFAAAGQAAAFACAFQABAFADADQADADAEABQAEACAEAAQAEAAADgCQAEgBADgDQADgDACgFQABgFAAgFQAAgGgBgFQgCgEgDgDQgDgDgEgCQgDgBgEAAQgEAAgEABg");
	this.shape_114.setTransform(883.9,230.9);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#999999").s().p("AAXA0IAAg9IgBgMIgDgJQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGADgIAJIAABIIgSAAIAAhlIAPAAIABAPIABAAQAIgIAHgEIAIgEIAJgBQAIAAAGACQAGADAEAFQAEAFACAIQACAHAAAKIAAA/g");
	this.shape_115.setTransform(873,228.5);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#999999").s().p("AgHBJIAAhlIAPAAIAABlgAgHg1QgEgDAAgFQAAgFAEgDQADgDAEAAQAFAAADADQAEADAAAFQAAAFgEADQgDAEgFAAQgEAAgDgEg");
	this.shape_116.setTransform(865.1,226.4);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#999999").s().p("AA1A0IAAg9IgBgMQgBgFgCgEQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGAEgIAIIAABIIgPAAIAAg9IgBgMIgDgJQgDgDgEgCQgEgBgFAAQgFAAgGAEQgHAEgHAIIAABIIgSAAIAAhlIAPAAIABAPIABAAQAHgIAIgEQAIgFAJAAQAFAAAGABQAEABAEADQAEAFAEAJQAIgJAIgFQAIgFAKAAQAHAAAGACQAGADAEAFQAEAFACAIQACAHgBAKIAAA/g");
	this.shape_117.setTransform(854.3,228.5);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#999999").s().p("AA1A0IAAg9IgBgMQgBgFgCgEQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGAEgIAIIAABIIgPAAIAAg9IgBgMIgDgJQgDgDgEgCQgEgBgFAAQgFAAgGAEQgHAEgHAIIAABIIgSAAIAAhlIAPAAIABAPIABAAQAHgIAIgEQAIgFAJAAQAGAAAEABQAFABAEADQAEAFADAJQAJgJAIgFQAIgFAKAAQAHAAAGACQAGADAEAFQAEAFACAIQACAHgBAKIAAA/g");
	this.shape_118.setTransform(837.3,228.5);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#999999").s().p("AgVA0QgFgCgEgEQgEgEgDgGQgCgFAAgGQAAgJAEgHQAEgGAHgDQAIgEAMgEQAKgCAQgDIgBgJIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJAEQgGACgIAFIgGgMQAIgGAJgDIALgEIAKgBQAJAAAHADQAHAEAEAFQAFAFACAJQACAHAAAKIAAA9IgPAAIgBgNIgBAAQgIAIgIADQgHAEgJABQgGgBgGgBgAABABQgHADgGADQgFADgCAEQgDAEAAAFQAAAJAFADQAFAEAIAAQAFAAAHgDQAHgDAHgHIAAgbQgMABgJABg");
	this.shape_119.setTransform(823.4,228.6);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#999999").s().p("AgbA0IAAhlIAPAAIABATIABAAQAFgKAGgGQAHgFAJAAQAGAAAFACIgDAPQgGgCgEAAQgIAAgGAGIgFAHIgFALIAABAg");
	this.shape_120.setTransform(815.9,228.5);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#999999").s().p("AgUBKQgJgCgFgDQgGgEgDgFQgDgFAAgHQAAgGAEgHQAEgFAHgFIAAgBQgEgDgCgEQgDgEAAgFQAAgGAEgEQADgFAEgDIAAAAQgGgGgDgGQgEgIAAgIQAAgJADgGQADgIAGgEQAFgFAHgCQAHgDAIAAQAGAAAGADIAkAAIAAANIgVAAQAEADACAGQACAGABAGQAAAIgEAHQgDAHgEAEQgGAFgHACQgGADgGAAQgIAAgIgEQgGAGgBAFQAAAFAFACQAEAEAKAAIARAAIAQABQAIACADACQAGAEABAEQADAFAAAHQAAAGgEAHQgDAGgHAFQgHAFgKADQgKADgJAAQgKAAgHgCgAgcAlQgCAEAAAFQAAAEACAEIAFAFQAEACAFABQAGACAHAAQAGAAAFgCQAHgBAEgEIAGgGQADgEAAgEQAAgHgFgDQgGgDgKAAIgQAAQgHAAgGgCQgFAFgDAEgAgMg9QgEACgDADQgDADgCAEQgBAFAAAGQAAAFABAFQACAFADADQAEADADABQAEACAFAAQADAAADgCQAEgBADgDQADgDACgFQABgFAAgFQAAgGgBgFQgCgEgDgDQgDgDgEgCQgDgBgDAAQgFAAgEABg");
	this.shape_121.setTransform(807,230.9);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#999999").s().p("AgQAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgLAEgLQAEgJAGgHQAHgIAJgDQAIgDAIgBQAJABAJADQAJADAGAIQAHAHADAJQAEALAAALQAAAMgEALQgDAJgHAHQgGAHgJAEQgJADgJABQgIgBgIgDgAgKgjQgGADgEAFQgEAFgCAHQgCAIAAAHQAAAJACAHQACAHAEAFQAEAFAGADQAFADAFAAQAGAAAGgDQAFgDAEgFQAEgFACgHQACgHAAgJQAAgHgCgIQgCgHgEgFQgEgFgFgDQgGgDgGAAQgFAAgFADg");
	this.shape_122.setTransform(796.1,228.6);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#999999").s().p("AgbA0IAAhlIAPAAIABATIABAAQAFgKAGgGQAHgFAJAAQAGAAAFACIgDAPQgGgCgEAAQgIAAgGAGIgFAHIgFALIAABAg");
	this.shape_123.setTransform(788.1,228.5);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#999999").s().p("AgrBKIAAiQIAOAAIABALIABAAQAIgGAHgEQAKgEAGAAQAJAAAJAEQAHADAFAHQAFAHADAKQADAJAAAMQAAANgEAJQgEAKgGAIQgGAGgIAEQgIAEgJAAQgFAAgIgDQgHgDgHgGIABASIAAAjgAgMg3QgGADgIAIIAAA0QAGAFAHADQAGACAGABQAEAAAGgDQAFgDAEgFQAEgGACgGQACgHABgKQAAgIgCgHQgBgHgEgFQgDgFgFgDQgGgDgGAAQgFABgHADg");
	this.shape_124.setTransform(778.6,230.7);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#999999").s().p("AgMAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgDAHgBQAKABAIADQAHADAGAGQAFAHADAJQACAJAAALIAAAHIhEAAQABAJACAGQADAHAEAFQAFAEAGADQAEACAIAAQAGAAAHgCQAGgBAGgEIAGALQgHAFgIADQgJADgKAAQgIgBgJgDgAAcgGQAAgIgCgGQgBgGgEgFQgDgEgFgBQgEgDgGAAQgEAAgFADQgFACgEAEQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_125.setTransform(764,228.6);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#999999").s().p("AgJAzIglhlIASAAIAUA5IAIAeIABAAIAJgeIAUg5IARAAIglBlg");
	this.shape_126.setTransform(754.3,228.6);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#999999").s().p("AgHBJIAAhlIAPAAIAABlgAgHg1QgEgDAAgFQAAgFAEgDQADgDAEAAQAFAAADADQAEADAAAFQAAAFgEADQgDAEgFAAQgEAAgDgEg");
	this.shape_127.setTransform(747.3,226.4);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#999999").s().p("AAABAQgFgCgDgFQgEgEgCgHQgBgGAAgIIAAg3IgPAAIAAgNIAPgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QABAKADAEQADAGAJAAQAEAAAIgDIAEANQgMAEgHAAQgJAAgEgDg");
	this.shape_128.setTransform(741.7,227.3);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#999999").s().p("AgKAyQgJgDgHgIQgGgHgDgJQgEgLgBgMQAAgLAFgLQAEgJAGgHQAIgIAJgDQAIgDAIgBQAKABAIADQAHADAFAFIgJAMQgFgEgEgCQgGgDgFAAQgHAAgEADQgGADgEAFQgFAFgCAHQgDAIAAAHQAAAJADAHQACAHAEAFQAFAFAGADQADADAHAAQAHAAAHgDQAFgDAGgFIAIAMQgIAGgIAEQgJADgJABQgIgBgJgDg");
	this.shape_129.setTransform(734,228.6);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#999999").s().p("AgVA0QgFgCgEgEQgEgEgDgGQgCgFAAgGQAAgJAEgHQAEgGAHgDQAIgEAMgEQAKgCAQgDIgBgJIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJAEQgGACgIAFIgGgMQAIgGAJgDIALgEIAKgBQAJAAAHADQAHAEAEAFQAFAFACAJQACAHAAAKIAAA9IgPAAIgBgNIgBAAQgIAIgIADQgHAEgJABQgGgBgGgBgAABABQgHADgGADQgFADgCAEQgDAEAAAFQAAAJAFADQAFAEAIAAQAFAAAHgDQAHgDAHgHIAAgbQgMABgJABg");
	this.shape_130.setTransform(723.9,228.6);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#999999").s().p("AgMAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgDAHgBQAKABAIADQAHADAGAGQAFAHADAJQACAJAAALIAAAHIhEAAQABAJACAGQADAHAEAFQAFAEAGADQAEACAIAAQAGAAAHgCQAGgBAGgEIAGALQgHAFgIADQgJADgKAAQgIgBgJgDgAAcgGQAAgIgCgGQgBgGgEgFQgDgEgFgBQgEgDgGAAQgEAAgFADQgFACgEAEQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_131.setTransform(714,228.6);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#999999").s().p("AAbBFIgfg7IgZAAIAAA7IgSAAIAAiJIAsAAQAJAAAIACQAJACAHAEQAGAGAEAHQADAHAAALQAAAIgCAGQgCAHgEAFQgEADgGADQgGADgHACIAkA9gAgdgCIAXAAQAGAAAHgCQAGgBAEgEQAEgDADgFQACgFAAgHQAAgHgCgFQgDgFgEgCQgEgDgGgCQgGgBgHAAIgXAAg");
	this.shape_132.setTransform(703.7,226.8);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#999999").s().p("AgOATQAIgEAFgGQADgHABgHIgDAAQgDAAgEgCQgDgEAAgFQAAgGADgDQAFgDADAAQAGgBAFAGQADAGAAAJQAAAGgBAFIgGALQgEAFgEAEQgEAEgHACg");
	this.shape_133.setTransform(687.5,234.4);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#999999").s().p("AgTAyQgKgFgHgGIAIgMQAHAHAHACQAIAEAGAAQALAAAFgFQAFgEAAgHQAAgEgDgDQgBgDgDgCQgGgDgJgEIgLgFIgJgEQgFgDgCgFQgDgFgBgHQAAgFADgGQACgFAFgEQAEgEAHgDQAHgBAGgBQAJABAJADQAHADAHAFIgJALQgFgEgFgCQgHgDgGAAQgHAAgFAFQgFADAAAHQAAAGAHAEQAEADAKAEIALAFIAKAEQAFAEADAEQACAGAAAHQAAAGgCAGQgDAFgEAEQgFAFgHACQgIACgIABQgJgBgKgDg");
	this.shape_134.setTransform(681,228.6);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#999999").s().p("AgDBLQgDgCgDgDQgEgFAAgMIAAiAIAQAAIAACBQAAAIAEAAIAEgBIADAOQgEABgGAAQgEAAgDgBg");
	this.shape_135.setTransform(674.8,226.3);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#999999").s().p("AgDBLQgDgCgDgDQgEgFAAgMIAAiAIAQAAIAACBQAAAIAEAAIAEgBIADAOQgEABgGAAQgEAAgDgBg");
	this.shape_136.setTransform(670,226.3);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#999999").s().p("AgVA0QgFgCgEgEQgEgEgDgGQgCgFAAgGQAAgJAEgHQAEgGAHgDQAIgEAMgEQAKgCAQgDIgBgJIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJAEQgGACgIAFIgGgMQAIgGAJgDIALgEIAKgBQAJAAAHADQAHAEAEAFQAFAFACAJQACAHAAAKIAAA9IgPAAIgBgNIgBAAQgIAIgIADQgHAEgJABQgGgBgGgBgAABABQgHADgGADQgFADgCAEQgDAEAAAFQAAAJAFADQAFAEAIAAQAFAAAHgDQAHgDAHgHIAAgbQgMABgJABg");
	this.shape_137.setTransform(661.8,228.6);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#999999").s().p("AgKAyQgJgDgHgIQgGgHgEgJQgDgLAAgMQAAgLAEgLQADgJAIgHQAHgIAIgDQAJgDAIgBQAJABAJADQAGADAHAFIgJAMQgFgEgFgCQgGgDgFAAQgHAAgEADQgGADgEAFQgEAFgDAHQgDAIABAHQgBAJADAHQADAHAEAFQAEAFAFADQAEADAHAAQAIAAAGgDQAGgDAEgFIAIAMQgHAGgIAEQgJADgJABQgIgBgJgDg");
	this.shape_138.setTransform(652.5,228.6);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#999999").s().p("AgMAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgDAHgBQAKABAIADQAHADAGAGQAFAHADAJQACAJAAALIAAAHIhEAAQABAJACAGQADAHAEAFQAFAEAGADQAEACAIAAQAGAAAHgCQAGgBAGgEIAGALQgHAFgIADQgJADgKAAQgIgBgJgDgAAcgGQAAgIgCgGQgBgGgEgFQgDgEgFgBQgEgDgGAAQgEAAgFADQgFACgEAEQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_139.setTransform(639,228.6);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f("#999999").s().p("AgbA0IAAhlIAPAAIABATIABAAQAFgKAGgGQAHgFAJAAQAGAAAFACIgDAPQgGgCgEAAQgIAAgGAGIgFAHIgFALIAABAg");
	this.shape_140.setTransform(631.5,228.5);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f("#999999").s().p("AgWAyQgGgDgEgFQgEgFgBgIQgCgHAAgKIAAg/IARAAIAAA9IABAMQABAFACAEQADADAEACQADABAGAAQAFAAAGgEQAHgEAHgJIAAhHIASAAIAABlIgPAAIgCgQIAAAAQgIAJgIAEQgEADgEABIgIABQgIAAgGgCg");
	this.shape_141.setTransform(621.7,228.7);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f("#999999").s().p("AgTBJQgIgEgFgHQgGgHgDgKQgDgKAAgNQAAgMAEgKQADgIAHgHQAGgHAIgEQAIgEAIAAQAHAAAHADQAGADAIAGIgBgSIAAgnIASAAIAACVIgPAAIgBgMIgBAAQgHAGgHAEQgJAEgGAAQgKAAgIgDgAgIgMQgFACgEAGQgEAEgCAGQgDAIAAAIQAAAJACAIQACAHAEAFQADAFAGADQAFADAFAAQAHAAAGgEQAHgDAGgIIAAgzQgGgGgHgDQgGgCgGAAQgEAAgGADg");
	this.shape_142.setTransform(610.2,226.3);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.f("#999999").s().p("AgMAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgDAHgBQAKABAIADQAHADAGAGQAFAHADAJQACAJAAALIAAAHIhEAAQABAJACAGQADAHAEAFQAFAEAGADQAEACAIAAQAGAAAHgCQAGgBAGgEIAGALQgHAFgIADQgJADgKAAQgIgBgJgDgAAcgGQAAgIgCgGQgBgGgEgFQgDgEgFgBQgEgDgGAAQgEAAgFADQgFACgEAEQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_143.setTransform(600.1,228.6);

	this.shape_144 = new cjs.Shape();
	this.shape_144.graphics.f("#999999").s().p("AgKAyQgJgDgHgIQgGgHgEgJQgDgLAAgMQgBgLAFgLQAEgJAGgHQAIgIAIgDQAJgDAIgBQAJABAJADQAGADAHAFIgJAMQgGgEgEgCQgGgDgFAAQgHAAgEADQgGADgEAFQgEAFgDAHQgDAIABAHQgBAJADAHQACAHAFAFQAEAFAGADQADADAHAAQAIAAAGgDQAGgDAEgFIAJAMQgIAGgIAEQgJADgJABQgIgBgJgDg");
	this.shape_144.setTransform(590.7,228.6);

	this.shape_145 = new cjs.Shape();
	this.shape_145.graphics.f("#999999").s().p("AgQAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgLAEgLQAEgJAGgHQAHgIAJgDQAIgDAIgBQAJABAJADQAJADAGAIQAHAHADAJQAEALAAALQAAAMgEALQgDAJgHAHQgGAHgJAEQgJADgJABQgIgBgIgDgAgKgjQgGADgEAFQgEAFgCAHQgCAIAAAHQAAAJACAHQACAHAEAFQAEAFAGADQAFADAFAAQAGAAAGgDQAFgDAEgFQAEgFACgHQACgHAAgJQAAgHgCgIQgCgHgEgFQgEgFgFgDQgGgDgGAAQgFAAgFADg");
	this.shape_145.setTransform(580.4,228.6);

	this.shape_146 = new cjs.Shape();
	this.shape_146.graphics.f("#999999").s().p("AgbA0IAAhlIAPAAIABATIABAAQAFgKAGgGQAHgFAJAAQAGAAAFACIgDAPQgGgCgEAAQgIAAgGAGIgFAHIgFALIAABAg");
	this.shape_146.setTransform(572.5,228.5);

	this.shape_147 = new cjs.Shape();
	this.shape_147.graphics.f("#999999").s().p("AgrBKIAAiQIAOAAIACALIAAAAQAIgGAIgEQAIgEAHAAQAKAAAHAEQAIADAFAHQAFAHADAKQACAJABAMQgBANgDAJQgEAKgGAIQgGAGgIAEQgIAEgJAAQgFAAgIgDQgHgDgGgGIAAASIAAAjgAgMg3QgGADgIAIIAAA0QAHAFAGADQAHACAFABQAFAAAEgDQAGgDAEgFQAEgGADgGQABgHAAgKQAAgIgBgHQgCgHgDgFQgDgFgFgDQgGgDgGAAQgFABgHADg");
	this.shape_147.setTransform(563,230.7);

	this.shape_148 = new cjs.Shape();
	this.shape_148.graphics.f("#999999").s().p("AgMAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgDAHgBQAKABAIADQAHADAGAGQAFAHADAJQACAJAAALIAAAHIhEAAQABAJACAGQADAHAEAFQAFAEAGADQAEACAIAAQAGAAAHgCQAGgBAGgEIAGALQgHAFgIADQgJADgKAAQgIgBgJgDgAAcgGQAAgIgCgGQgBgGgEgFQgDgEgFgBQgEgDgGAAQgEAAgFADQgFACgEAEQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_148.setTransform(548.3,228.6);

	this.shape_149 = new cjs.Shape();
	this.shape_149.graphics.f("#999999").s().p("AAABAQgFgCgEgFQgDgEgCgHQgBgGAAgIIAAg3IgPAAIAAgNIAPgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QAAAKAEAEQADAGAJAAQAEAAAIgDIAEANQgMAEgHAAQgJAAgEgDg");
	this.shape_149.setTransform(540.1,227.3);

	this.shape_150 = new cjs.Shape();
	this.shape_150.graphics.f("#999999").s().p("AgQAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgLAEgLQAEgJAGgHQAHgIAJgDQAIgDAIgBQAJABAJADQAJADAGAIQAHAHADAJQAEALAAALQAAAMgEALQgDAJgHAHQgGAHgJAEQgJADgJABQgIgBgIgDgAgKgjQgGADgEAFQgEAFgCAHQgCAIAAAHQAAAJACAHQACAHAEAFQAEAFAGADQAFADAFAAQAGAAAGgDQAFgDAEgFQAEgFACgHQACgHAAgJQAAgHgCgIQgCgHgEgFQgEgFgFgDQgGgDgGAAQgFAAgFADg");
	this.shape_150.setTransform(531.2,228.6);

	this.shape_151 = new cjs.Shape();
	this.shape_151.graphics.f("#999999").s().p("AA1A0IAAg9IgBgMQgBgFgDgEQgCgDgDgCQgEgBgFAAQgGAAgGAEQgHAEgGAIIAABIIgQAAIAAg9IgBgMIgEgJQgCgDgEgCQgEgBgEAAQgGAAgHAEQgGAEgHAIIAABIIgRAAIAAhlIAOAAIACAPIAAAAQAHgIAHgEQAJgFAJAAQAFAAAFABQAFABADADQAFAFADAJQAJgJAHgFQAKgFAIAAQAIAAAGACQAGADAEAFQAEAFACAIQACAHAAAKIAAA/g");
	this.shape_151.setTransform(517.3,228.5);

	this.shape_152 = new cjs.Shape();
	this.shape_152.graphics.f("#999999").s().p("AgMAyQgJgEgHgHQgGgHgEgJQgEgLAAgMQAAgKAEgLQAEgJAGgIQAHgHAIgEQAIgDAHgBQAKABAIADQAHADAGAGQAFAHADAJQACAJAAALIAAAHIhEAAQABAJACAGQADAHAEAFQAFAEAGADQAEACAIAAQAGAAAHgCQAGgBAGgEIAGALQgHAFgIADQgJADgKAAQgIgBgJgDgAAcgGQAAgIgCgGQgBgGgEgFQgDgEgFgBQgEgDgGAAQgEAAgFADQgFACgEAEQgEAEgDAGQgCAGgBAIIA1AAIAAAAg");
	this.shape_152.setTransform(503.8,228.6);

	this.shape_153 = new cjs.Shape();
	this.shape_153.graphics.f("#999999").s().p("AAbBFIgfg7IgZAAIAAA7IgSAAIAAiJIAsAAQAJAAAIACQAJACAHAEQAGAGAEAHQADAHAAALQAAAIgCAGQgCAHgEAFQgEADgGADQgGADgHACIAkA9gAgdgCIAXAAQAGAAAHgCQAGgBAEgEQAEgDADgFQACgFAAgHQAAgHgCgFQgDgFgEgCQgEgDgGgCQgGgBgHAAIgXAAg");
	this.shape_153.setTransform(493.5,226.8);

	this.shape_154 = new cjs.Shape();
	this.shape_154.graphics.f("#999999").s().p("AgOATQAIgEAFgGQADgHABgHIgDAAQgDAAgEgCQgDgEAAgFQAAgGADgDQAFgDADAAQAGgBAFAGQADAGAAAJQAAAGgBAFIgGALQgEAFgEAEQgEAEgGACg");
	this.shape_154.setTransform(477.3,234.4);

	this.shape_155 = new cjs.Shape();
	this.shape_155.graphics.f("#999999").s().p("AgNBJQgIgDgGgGIgBAAIgCAKIgNAAIAAiVIARAAIAAApIAAATQAHgHAHgEQAKgEAFAAQALAAAHAEQAIAEAFAGQAFAHADAJQACAJABAMQgBAMgDALQgEAKgGAIQgGAHgIAEQgIADgJAAQgFAAgIgDgAgMgMQgHAEgHAHIAAA0QAGAFAHADQAHADAFAAQAFAAAFgDQAFgDAEgFQAEgGADgHQACgIAAgJQgBgJgBgHQgCgFgDgFQgDgFgFgCQgGgDgGAAQgFAAgHADg");
	this.shape_155.setTransform(469.7,226.3);

	this.shape_156 = new cjs.Shape();
	this.shape_156.graphics.f("#999999").s().p("AgWAyQgGgDgEgFQgEgFgBgIQgCgHAAgKIAAg/IARAAIAAA9IABAMQABAFACAEQADADAEACQADABAGAAQAFAAAGgEQAHgEAHgJIAAhHIASAAIAABlIgPAAIgBgQIgBAAQgIAJgIAEQgDADgFABIgIABQgIAAgGgCg");
	this.shape_156.setTransform(458.2,228.7);

	this.shape_157 = new cjs.Shape();
	this.shape_157.graphics.f("#999999").s().p("AgMBGIgNgEQgGgCgGgEQgFgEgEgFIAKgNQAIAIAJAGQALAEAIAAQAHAAAGgCQAFgBAEgDQADgDACgEQACgFABgEQgBgGgCgDQgBgEgDgDQgFgEgMgFIgRgJIgKgDQgGgDgDgEQgFgFgCgFQgDgHAAgHQAAgHADgIQAEgGAGgFQAFgFAJgDQAHgCAIgBQAIABAPAEQAKAEAIAJIgKALQgGgHgIgDQgIgDgJAAQgEAAgFACQgFAAgDADQgDADgCAEQgCADAAAFQAAAFACAEQABADAEADQAFADAKAGIATAIIALADIAKAIQADAFACAFQACAHABAHQAAAIgEAHQgDAIgHAFQgFAFgJAEQgJACgLAAIgMgBg");
	this.shape_157.setTransform(447.5,226.8);

	this.shape_158 = new cjs.Shape();
	this.shape_158.graphics.f("#999999").s().p("AghBcIA2i3IANAAIg2C3g");
	this.shape_158.setTransform(438.6,227.9);

	this.shape_159 = new cjs.Shape();
	this.shape_159.graphics.f("#999999").s().p("AgNBJQgHgDgIgGIAAAAIgBAKIgPAAIAAiVIASAAIAAApIgBATQAIgHAIgEQAIgEAHAAQAJAAAJAEQAHAEAFAGQAFAHADAJQADAJgBAMQABAMgEALQgDAKgHAIQgGAHgIAEQgIADgJAAQgFAAgIgDgAgMgMQgHAEgHAHIAAA0QAGAFAHADQAHADAFAAQAFAAAEgDQAGgDAEgFQAEgGACgHQACgIAAgJQABgJgCgHQgCgFgDgFQgDgFgFgCQgFgDgHAAQgFAAgHADg");
	this.shape_159.setTransform(430,226.3);

	this.shape_160 = new cjs.Shape();
	this.shape_160.graphics.f("#999999").s().p("AgWAyQgGgDgEgFQgEgFgCgIQgBgHAAgKIAAg/IARAAIAAA9IABAMQABAFACAEQADADADACQAEABAFAAQAGAAAHgEQAFgEAIgJIAAhHIARAAIAABlIgOAAIgCgQIAAAAQgIAJgIAEQgEADgEABIgIABQgIAAgGgCg");
	this.shape_160.setTransform(418.5,228.7);

	this.shape_161 = new cjs.Shape();
	this.shape_161.graphics.f("#999999").s().p("AguBFIAAiJIArAAQAKAAAJACQAKACAGAFQAIAFADAIQADAHABAMQgBALgDAIQgEAIgHADQgGAGgKACQgJADgKAAIgZAAIAAA3gAgcAAIAXAAQAHAAAHAAQAHgCAEgEQAFgDACgGQACgFAAgHQAAgHgCgGQgCgFgFgDQgFgDgGgCQgHgBgHAAIgXAAg");
	this.shape_161.setTransform(407.8,226.8);

	this.shape_162 = new cjs.Shape();
	this.shape_162.graphics.f("#999999").s().p("AgOATQAJgEAEgGQAEgHgBgHIgBAAQgEAAgDgCQgEgEAAgFQAAgGAEgDQAEgDADAAQAHgBAEAGQADAGAAAJQAAAGgCAFIgFALQgDAFgFAEQgEAEgHACg");
	this.shape_162.setTransform(391.7,234.4);

	this.shape_163 = new cjs.Shape();
	this.shape_163.graphics.f("#999999").s().p("AgKAyQgJgDgGgIQgHgHgDgJQgFgLAAgMQABgLAEgLQADgJAIgHQAGgIAKgDQAIgDAJgBQAIABAJADQAHADAFAFIgJAMQgEgEgFgCQgFgDgGAAQgHAAgEADQgGADgEAFQgFAFgCAHQgCAIgBAHQABAJACAHQACAHAEAFQAFAFAFADQAEADAIAAQAGAAAHgDQAFgDAFgFIAIAMQgGAGgJAEQgJADgJABQgIgBgJgDg");
	this.shape_163.setTransform(385,228.6);

	this.shape_164 = new cjs.Shape();
	this.shape_164.graphics.f("#999999").s().p("AAXA0IAAg9IgBgMIgDgJQgDgDgEgCQgDgBgFAAQgGAAgGAEQgGADgIAJIAABIIgSAAIAAhlIAPAAIABAPIABAAQAIgIAHgEIAIgEIAJgBQAIAAAGACQAGADAEAFQAEAFACAIQACAHAAAKIAAA/g");
	this.shape_164.setTransform(374.8,228.5);

	this.shape_165 = new cjs.Shape();
	this.shape_165.graphics.f("#999999").s().p("AgpBHIADgOIAIACQAEAAAEgCIAHgFQAFgFAEgKIACgIIgqhlIASAAIAWA5IAIAbIABAAIAIgbIATg5IARAAIgoBtQgCAIgDAGQgCAHgEAFQgFAFgGACQgHADgHAAQgGAAgGgCg");
	this.shape_165.setTransform(364.6,230.8);

	this.shape_166 = new cjs.Shape();
	this.shape_166.graphics.f("#999999").s().p("AgTAyQgKgFgIgGIAJgMQAHAHAHACQAIAEAHAAQAJAAAFgFQAGgEAAgHQAAgEgCgDQgCgDgEgCQgEgDgKgEIgLgFIgKgEQgEgDgDgFQgDgFABgHQAAgFACgGQACgFAFgEQAEgEAHgDQAHgBAGgBQAJABAJADQAHADAHAFIgIALQgGgEgGgCQgFgDgHAAQgHAAgFAFQgFADAAAHQAAAGAIAEQADADAKAEIAMAFIAKAEQAEAEADAEQADAGAAAHQgBAGgCAGQgCAFgFAEQgFAFgHACQgIACgIABQgJgBgKgDg");
	this.shape_166.setTransform(355.7,228.6);

	this.shape_167 = new cjs.Shape();
	this.shape_167.graphics.f("#999999").s().p("AgVA0QgFgCgEgEQgEgEgDgGQgCgFAAgGQAAgJAEgHQAEgGAHgDQAIgEAMgEQAKgCAQgDIgBgJIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJAEQgGACgIAFIgGgMQAIgGAJgDIALgEIAKgBQAJAAAHADQAHAEAEAFQAFAFACAJQACAHAAAKIAAA9IgPAAIgBgNIgBAAQgIAIgIADQgHAEgJABQgGgBgGgBgAABABQgHADgGADQgFADgCAEQgDAEAAAFQAAAJAFADQAFAEAIAAQAFAAAHgDQAHgDAHgHIAAgbQgMABgJABg");
	this.shape_167.setTransform(342.5,228.6);

	this.shape_168 = new cjs.Shape();
	this.shape_168.graphics.f("#999999").s().p("AAABAQgFgCgDgFQgEgEgCgHQgBgGAAgIIAAg3IgQAAIAAgNIAQgBIADgdIAMAAIAAAdIAcAAIAAAOIgcAAIAAA4QABAKADAEQADAGAKAAQADAAAIgDIAEANQgMAEgIAAQgIAAgEgDg");
	this.shape_168.setTransform(334.4,227.3);

	this.shape_169 = new cjs.Shape();
	this.shape_169.graphics.f("#999999").s().p("AgVA0QgFgCgEgEQgEgEgDgGQgCgFAAgGQAAgJAEgHQAEgGAHgDQAIgEAMgEQAKgCAQgDIgBgJIgDgIQgCgEgEgCQgFgCgGAAQgGAAgJAEQgGACgIAFIgGgMQAIgGAJgDIALgEIAKgBQAJAAAHADQAHAEAEAFQAFAFACAJQACAHAAAKIAAA9IgPAAIgBgNIgBAAQgIAIgIADQgHAEgJABQgGgBgGgBgAABABQgHADgGADQgFADgCAEQgDAEAAAFQAAAJAFADQAFAEAIAAQAFAAAHgDQAHgDAHgHIAAgbQgMABgJABg");
	this.shape_169.setTransform(325.6,228.6);

	this.shape_170 = new cjs.Shape();
	this.shape_170.graphics.f("#999999").s().p("AgxBFIAAiJIAjAAIAOABIAMAEQAGACAGADIAJAIQAEAEADAFIAFANIAEANIABAPQgCAUgDAIIgFANIgHAKIgJAIQgFADgGACIgNAEIgNABgAgfA2IAQAAQAMAAAHgDQAJgEAGgHQAGgHADgKQADgLAAgMQAAgNgDgKQgDgJgGgIQgGgGgJgEQgHgDgMAAIgQAAg");
	this.shape_170.setTransform(314.8,226.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_170},{t:this.shape_169},{t:this.shape_168},{t:this.shape_167},{t:this.shape_166},{t:this.shape_165},{t:this.shape_164},{t:this.shape_163},{t:this.shape_162},{t:this.shape_161},{t:this.shape_160},{t:this.shape_159},{t:this.shape_158},{t:this.shape_157},{t:this.shape_156},{t:this.shape_155},{t:this.shape_154},{t:this.shape_153},{t:this.shape_152},{t:this.shape_151},{t:this.shape_150},{t:this.shape_149},{t:this.shape_148},{t:this.shape_147},{t:this.shape_146},{t:this.shape_145},{t:this.shape_144},{t:this.shape_143},{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]}).to({state:[]},1).wait(49));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(900.4,455.6,879.6,300.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;